name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on:  ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: creating and activating virtualenv
        run: |
          pip3 install virtualenv 
          virtualenv venv
          source venv/bin/activate
      - name: install dependencies
        run: |
          pip install dvc[s3]
          pip install -r requirements_test.txt
      - name: Test Api
        run: |
         dvc pull model/model.pkl -r model_tracker
         pytest tests.py








